<?php
declare(strict_types=1);

use App\ViewRenderer;
use Prismic\Document\Fragment\RichText;
use Prismic\Document\Fragment\Slice;
use Prismic\Document\Fragment\TextElement;
use Prismic\Serializer\HtmlSerializer;

/** @var ViewRenderer $this */

$slice = $this->slice ?? null;
assert($slice instanceof Slice);

$serializer = new HtmlSerializer($this->linkResolver());

$title = $slice->primary()->get('title');
if (! $title instanceof RichText || $title->isEmpty()) {
    return;
}

$leadText = $slice->primary()->get('lead');
$lead = $leadText instanceof RichText ? $leadText->first() : null;
$lead = $lead instanceof TextElement ? sprintf(
    '<p class="lead">%s</p>',
    $this->escapeHtml($lead->text())
) : '';


?>

<section class="illustration-header">
    <div class="container">
        <div class="caption">
            <?= $serializer($title) ?>
            <?= $lead ?>
        </div>
        <div class="illustration">
            <?= $serializer($slice->primary()->get('image')) ?>
        </div>
    </div>
</section>
