<?php
declare(strict_types=1);

use App\ViewRenderer;
use Prismic\Document\Fragment\RichText;
use Prismic\Document\Fragment\Slice;
use Prismic\Document\Fragment\TextElement;
use Prismic\Serializer\HtmlSerializer;

/** @var ViewRenderer $this */

$slice = $this->slice ?? null;
assert($slice instanceof Slice);

$serializer = new HtmlSerializer($this->linkResolver());

?>

<section class="illustration-header">
    <div class="container">
        <div class="caption">
            <?= $serializer($slice->primary()->get('title')) ?>
            <?= $serializer($slice->primary()->get('lead')) ?>
        </div>
        <div class="illustration">
            <?= $serializer($slice->primary()->get('image')) ?>
        </div>
    </div>
</section>
