<?php
declare(strict_types=1);

use App\ViewRenderer;
use Prismic\Document;

/** @var ViewRenderer $this */

$prismicToolbarUrl = sprintf(
    'https://static.cdn.prismic.io/prismic.min.js?repo=%s&new=true',
    $this->repositoryInformation()->host()
);

$document = $this->document ?? null;

$language = 'en-gb';
$canonical = $this->url();

if ($document instanceof Document) {
    $language = $document->lang();
    $canonical = $this->linkResolver($document);
}

$this->headLink()->prependStylesheet('/assets/css/main-2080cca632c04464e2d05a686320d71e-9e438296-a108-11eb-8680-3c7d0a043928.css');
$this->inlineScript()->appendFile('/assets/js/main-d2fa57fa6dc13b0d0456ca1c38603b20-16f4e2cc-aa54-11ea-8ad1-787b8ac8307f.js');
$this->inlineScript()->appendFile($prismicToolbarUrl, 'text/javascript', ['async' => true, 'defer' => true]);


$this->headLink([
    'rel' => 'canonical',
    'href' => $canonical,
]);

// Syntax highlighting with Prism
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/themes/prism-okaidia.min.css');
$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/prism.min.js');
$this->inlineScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/plugins/autoloader/prism-autoloader.min.js');
?>
<!DOCTYPE html>
<html class="no-js" lang="<?= $language ?>">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <?php
    echo $this->headTitle() . PHP_EOL;
    echo $this->headMeta()->setIndent("\t")->setSeparator("\n") . PHP_EOL;
    echo $this->headLink()->setIndent("\t")->setSeparator("\n");
    echo $this->googleAnalytics();
    ?>

</head>
<body>
    <header>
        <div class="container">
            <div class="main-nav">
                <?= $this->linkList()->renderToMarkup($this->mainMenu()) ?>
            </div>
        </div>
    </header>
    <main>
        <?= $this->content ?? null ?>
    </main>
    <footer>
        <div class="container">
            <form method="get" action="<?= $this->url('search') ?>">
                <label for="site-wide-search">Search:</label><input
                    id="site-wide-search"
                    name="term"
                    type="text"
                    placeholder="Type some terms and hit enter…"
                    value="<?= $this->escapeHtmlAttr($this->searchTerm ?? '') ?>"
                >
            </form>

            <?= $this->linkList()->renderToMarkup($this->mainMenu()) ?>
            <p>
                <a href="<?= $this->url('throw-it') ?>">Throw an Exception!</a>
                |
                <a href="/gimme/a/404">Find something that isn’t there…</a>
            </p>
            <p>
                <a href="https://docs.mezzio.dev">Mezzio Documentation</a>
                |
                <a href="https://prismic.io/">Prismic Headless CMS</a>
            </p>
            <p>
                Brought to you by <a href="https://netglue.uk">Net Glue Ltd in sunny Devon</a>.
                Illustrations by <a href="https://undraw.co">unDraw.co</a>
            </p>
        </div>
    </footer>
    <?=$this->inlineScript()?>
</body>
</html>
