name: "Composer Require Checker"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  composer-require-checker:
    name: "Composer Require Checker"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1

      - name: "Get Composer cache directory"
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-locked-7.4-${{ hashFiles('composer.*') }}
          restore-keys: composer-locked-7.4-${{ hashFiles('composer.*') }}

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Install require checker"
        run: "composer require --dev maglnet/composer-require-checker"

      - name: "Check"
        run: "vendor/bin/composer-require-checker check"
