name: PHPUnit Test Suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest

    env:
      php_extentions: mbstring,curl,json,intl,apcu

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4', '8.0']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php_extentions }}
          coverage: pcov
          ini-values: apc.enabled=1, apc.enable_cli=1, apc.use_request_time=0, pcov.enabled=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: Run Tests
        run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
